services:
  - type: web
    name: skytrack-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        scope: run
        value: ${MONGODB_URI}
      - key: SESSION_SECRET
        scope: run
        value: ${SESSION_SECRET}
      - key: PORT
        scope: run
        value: 3000
